import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--surface-variant)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-background": "var(--on-background)",
        "error-container": "var(--error-container)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        error: "var(--error)",
        "on-error": "var(--on-error)",
        background: "var(--background)",
        "surface-container-high": "var(--surface-container-high)",
        surface: "var(--surface)",
        "on-primary": "var(--on-primary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-secondary": "var(--on-secondary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-surface": "var(--on-surface)",
        "on-error-container": "var(--on-error-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        outline: "var(--outline)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "inverse-surface": "var(--inverse-surface)",
        "secondary-container": "var(--secondary-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container": "var(--surface-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        secondary: "var(--secondary)",
        tertiary: "var(--tertiary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "surface-bright": "var(--surface-bright)",
        primary: "var(--primary)",
        "primary-container": "var(--primary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-tint": "var(--surface-tint)",
        "on-secondary-container": "var(--on-secondary-container)",
        "inverse-primary": "var(--inverse-primary)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
      },
      borderRadius: {
        DEFAULT: "0px", // Forced to 0px to maintain pixel-art brutalism
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      spacing: {
        "pixel-unit": "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "border-width": "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Mono", "monospace"],
        "body-md": ["Courier Prime", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "headline-lg": ["Space Mono", "monospace"],
        "body-lg": ["Courier Prime", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-1px", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
